import type { MaterialId, MaterialStyle, MaterialStyles, TextureKind } from "./types";
import { MATERIAL_LABELS } from "./types";

export const MATERIAL_CATALOG: Record<MaterialId, MaterialStyle> = {
  plaster: {
    color: "#d8d2c6",
    roughness: 0.88,
    metalness: 0.02,
    opacity: 1,
    transparent: false,
    texture: "plaster",
    scale: 2.4,
  },
  concrete: {
    color: "#8c887f",
    roughness: 0.92,
    metalness: 0.04,
    opacity: 1,
    transparent: false,
    texture: "concrete",
    scale: 1.8,
  },
  wood: {
    color: "#8a6848",
    roughness: 0.72,
    metalness: 0.02,
    opacity: 1,
    transparent: false,
    texture: "wood",
    scale: 1.1,
  },
  glass: {
    color: "#b7d0d4",
    roughness: 0.08,
    metalness: 0.12,
    opacity: 0.28,
    transparent: true,
    texture: "glass",
    scale: 2,
  },
  brick: {
    color: "#8a5340",
    roughness: 0.94,
    metalness: 0.02,
    opacity: 1,
    transparent: false,
    texture: "brick",
    scale: 0.52,
  },
  metal: {
    color: "#6a6e72",
    roughness: 0.32,
    metalness: 0.78,
    opacity: 1,
    transparent: false,
    texture: "metal",
    scale: 1.4,
  },
  terracotta: {
    color: "#9a4e32",
    roughness: 0.82,
    metalness: 0.02,
    opacity: 1,
    transparent: false,
    texture: "terracotta",
    scale: 0.38,
  },
  stone: {
    color: "#b3ada2",
    roughness: 0.86,
    metalness: 0.04,
    opacity: 1,
    transparent: false,
    texture: "stone",
    scale: 1.15,
  },
  water: {
    color: "#2f5c62",
    roughness: 0.12,
    metalness: 0.18,
    opacity: 0.55,
    transparent: true,
    texture: "water",
    scale: 2.8,
  },
  vegetation: {
    color: "#3a5538",
    roughness: 0.9,
    metalness: 0,
    opacity: 1,
    transparent: false,
    texture: "vegetation",
    scale: 1.3,
  },
  darkwood: {
    color: "#4a3426",
    roughness: 0.7,
    metalness: 0.04,
    opacity: 1,
    transparent: false,
    texture: "wood",
    scale: 0.9,
  },
  white: {
    color: "#f2efe8",
    roughness: 0.8,
    metalness: 0.02,
    opacity: 1,
    transparent: false,
    texture: "plaster",
    scale: 2.6,
  },
  marble: {
    color: "#e8e4dc",
    roughness: 0.22,
    metalness: 0.08,
    opacity: 1,
    transparent: false,
    texture: "stone",
    scale: 1.6,
  },
  zinc: {
    color: "#8a9598",
    roughness: 0.38,
    metalness: 0.72,
    opacity: 1,
    transparent: false,
    texture: "metal",
    scale: 1.2,
  },
  parquet: {
    color: "#9a7048",
    roughness: 0.62,
    metalness: 0.02,
    opacity: 1,
    transparent: false,
    texture: "wood",
    scale: 0.7,
  },
  lime: {
    color: "#e4dcc8",
    roughness: 0.9,
    metalness: 0.01,
    opacity: 1,
    transparent: false,
    texture: "plaster",
    scale: 3.2,
  },
  corten: {
    color: "#8a4a2a",
    roughness: 0.7,
    metalness: 0.45,
    opacity: 1,
    transparent: false,
    texture: "metal",
    scale: 1.6,
  },
  copper: {
    color: "#b87333",
    roughness: 0.28,
    metalness: 0.82,
    opacity: 1,
    transparent: false,
    texture: "metal",
    scale: 1.1,
  },
  slate: {
    color: "#3d4450",
    roughness: 0.78,
    metalness: 0.08,
    opacity: 1,
    transparent: false,
    texture: "stone",
    scale: 0.7,
  },
  gravel: {
    color: "#9a9488",
    roughness: 0.96,
    metalness: 0.02,
    opacity: 1,
    transparent: false,
    texture: "concrete",
    scale: 0.9,
  },
  clt: {
    color: "#c4a574",
    roughness: 0.68,
    metalness: 0.02,
    opacity: 1,
    transparent: false,
    texture: "wood",
    scale: 1.8,
  },
  polycarb: {
    color: "#c5d8dc",
    roughness: 0.18,
    metalness: 0.06,
    opacity: 0.42,
    transparent: true,
    texture: "glass",
    scale: 1.4,
  },
  travertine: {
    color: "#d8cbb8",
    roughness: 0.64,
    metalness: 0.04,
    opacity: 1,
    transparent: false,
    texture: "stone",
    scale: 1.3,
  },
  stucco: {
    color: "#ece6d8",
    roughness: 0.92,
    metalness: 0.01,
    opacity: 1,
    transparent: false,
    texture: "plaster",
    scale: 2.8,
  },
};

export const TEXTURE_LABELS: Record<TextureKind, string> = {
  smooth: "Lisse",
  plaster: "Enduit",
  concrete: "Granulat",
  wood: "Fil du bois",
  brick: "Appareil brique",
  stone: "Pierre",
  terracotta: "Tuiles",
  metal: "Brossé",
  water: "Eau",
  vegetation: "Feuillage",
  glass: "Reflet",
};

export function resolveMaterial(id: MaterialId, overrides?: MaterialStyles): MaterialStyle {
  return { ...MATERIAL_CATALOG[id], ...overrides?.[id] };
}

export const MATERIAL_COLORS: Record<MaterialId, string> = Object.fromEntries(
  (Object.keys(MATERIAL_CATALOG) as MaterialId[]).map((id) => [id, MATERIAL_CATALOG[id].color]),
) as Record<MaterialId, string>;

export const MATERIAL_PROPS: Record<
  MaterialId,
  { roughness: number; metalness: number; opacity: number; transparent: boolean }
> = Object.fromEntries(
  (Object.keys(MATERIAL_CATALOG) as MaterialId[]).map((id) => {
    const m = MATERIAL_CATALOG[id];
    return [id, { roughness: m.roughness, metalness: m.metalness, opacity: m.opacity, transparent: m.transparent }];
  }),
) as Record<MaterialId, { roughness: number; metalness: number; opacity: number; transparent: boolean }>;

export function materialLabel(id: MaterialId): string {
  return MATERIAL_LABELS[id];
}

export const ROOM_HATCH: Record<string, string> = {
  living: "#c9c2b0",
  kitchen: "#b7c4b8",
  bedroom: "#c3b8b2",
  bath: "#b4c3c6",
  wc: "#b4c3c6",
  entry: "#cfc9bb",
  corridor: "#c8c3b8",
  office: "#c0bbae",
  dining: "#c9c2b0",
  storage: "#b8b3a8",
  laundry: "#b8c0c2",
  terrace: "#9aa08c",
  patio: "#8f9a82",
  garage: "#a8a49c",
  studio: "#b9b0a4",
  dressing: "#cfc6b8",
  cellar: "#8a8478",
  gym: "#a8b4aa",
  other: "#c4bfb4",
};
