/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCopilotRouteImport } from './routes/api/copilot'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as StudioProjectIdRouteImport } from './routes/studio.$projectId'
import { Route as ApiGeoParcelleRouteImport } from './routes/api/geo.parcelle'
import { Route as ApiGeoParcelleAtRouteImport } from './routes/api/geo.parcelle-at'
import { Route as ApiGeoSearchRouteImport } from './routes/api/geo.search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotRoute = ApiCopilotRouteImport.update({
  id: '/api/copilot',
  path: '/api/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioProjectIdRoute = StudioProjectIdRouteImport.update({
  id: '/studio/$projectId',
  path: '/studio/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeoParcelleRoute = ApiGeoParcelleRouteImport.update({
  id: '/api/geo/parcelle',
  path: '/api/geo/parcelle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeoParcelleAtRoute = ApiGeoParcelleAtRouteImport.update({
  id: '/api/geo/parcelle-at',
  path: '/api/geo/parcelle-at',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeoSearchRoute = ApiGeoSearchRouteImport.update({
  id: '/api/geo/search',
  path: '/api/geo/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/rtc': typeof ApiRtcRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/api/geo/parcelle': typeof ApiGeoParcelleRoute
  '/api/geo/parcelle-at': typeof ApiGeoParcelleAtRoute
  '/api/geo/search': typeof ApiGeoSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/rtc': typeof ApiRtcRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/api/geo/parcelle': typeof ApiGeoParcelleRoute
  '/api/geo/parcelle-at': typeof ApiGeoParcelleAtRoute
  '/api/geo/search': typeof ApiGeoSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/rtc': typeof ApiRtcRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/api/geo/parcelle': typeof ApiGeoParcelleRoute
  '/api/geo/parcelle-at': typeof ApiGeoParcelleAtRoute
  '/api/geo/search': typeof ApiGeoSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/copilot'
    | '/api/rtc'
    | '/studio/$projectId'
    | '/api/geo/parcelle'
    | '/api/geo/parcelle-at'
    | '/api/geo/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/copilot'
    | '/api/rtc'
    | '/studio/$projectId'
    | '/api/geo/parcelle'
    | '/api/geo/parcelle-at'
    | '/api/geo/search'
  id:
    | '__root__'
    | '/'
    | '/api/copilot'
    | '/api/rtc'
    | '/studio/$projectId'
    | '/api/geo/parcelle'
    | '/api/geo/parcelle-at'
    | '/api/geo/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCopilotRoute: typeof ApiCopilotRoute
  ApiRtcRoute: typeof ApiRtcRoute
  StudioProjectIdRoute: typeof StudioProjectIdRoute
  ApiGeoParcelleRoute: typeof ApiGeoParcelleRoute
  ApiGeoParcelleAtRoute: typeof ApiGeoParcelleAtRoute
  ApiGeoSearchRoute: typeof ApiGeoSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot': {
      id: '/api/copilot'
      path: '/api/copilot'
      fullPath: '/api/copilot'
      preLoaderRoute: typeof ApiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$projectId': {
      id: '/studio/$projectId'
      path: '/studio/$projectId'
      fullPath: '/studio/$projectId'
      preLoaderRoute: typeof StudioProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geo/parcelle': {
      id: '/api/geo/parcelle'
      path: '/api/geo/parcelle'
      fullPath: '/api/geo/parcelle'
      preLoaderRoute: typeof ApiGeoParcelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geo/parcelle-at': {
      id: '/api/geo/parcelle-at'
      path: '/api/geo/parcelle-at'
      fullPath: '/api/geo/parcelle-at'
      preLoaderRoute: typeof ApiGeoParcelleAtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geo/search': {
      id: '/api/geo/search'
      path: '/api/geo/search'
      fullPath: '/api/geo/search'
      preLoaderRoute: typeof ApiGeoSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCopilotRoute: ApiCopilotRoute,
  ApiRtcRoute: ApiRtcRoute,
  StudioProjectIdRoute: StudioProjectIdRoute,
  ApiGeoParcelleRoute: ApiGeoParcelleRoute,
  ApiGeoParcelleAtRoute: ApiGeoParcelleAtRoute,
  ApiGeoSearchRoute: ApiGeoSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
